name: "Install Dotrun Action"
author: "Canonical webteam <webteam@canonical.com>"
description: "Installs and configures Dotrun"
branding:
  icon: "package"
  color: "green"
runs:
  using: "composite"
  steps:
    - name: Install and configure Dotrun
      run: |
        sudo rm -rf /etc/docker
        sudo snap install dotrun
      shell: bash
